backend:
  name: git-gateway
  branch: main

media_folder: "assets/img-cuts" # Folder for uploaded images
public_folder: "/assets/img-cuts"

collections:
  - name: "site_content"
    label: "Site Content"
    files:
      - label: "Header"
        name: "header"
        file: "content/header.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }